appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: F269Szy4CWrnFIpFSLNtcu2wbSmrdryH69Dj0MjYCPcZI3LN82POKm6wQxDIB7cLgvbI7/81ji48vg1Ppu0xuLHG3N6DXSzNPZFnXUJd4OouN1Zpwxhm7zu2nY0PM/UrzofjX3hc+5uJNw1mDwkvaDSLAikHUuux10bTLUlx3b1GCdSWlRjMKGtDrsfraiBI7JjIvTmsyMw4jTxzwreEp5ym/9PIsVRAzrWfgoH+2IYPdRCGaE/+E4suO0jnwgIeRlvAeo1azVouiVffeSz95646zxhvIZzoKnD4rIZqu9q0GnAA3YdibQZBwlWvm5p7WsrzfTV93jd2VlCF6SbQ64Eiuk5jDFx7gGn6RIfTM35TXzP+6PvxHyS9Mnxi51A0pqgqjAaeq6DpI5nUgpNQ1vmTwRUWyAcHHPDjMjiFNzULxbRRvdRkfJtBnFHNsZvX8nJ5pTbl4a8OLYTTHa8rEnU7YPy8zZ00izV9wwR8Ur36aiNO8N94JuSPONE6/c5xohdFEk0fcKawRf0ZMBDGvhGrGJTQcnUsOZfesotzTZm/9k7R93oa95dagl5iWqfLkud10t2ukt999/Cm025wpOp0wdOGLEI87BMBtCHiURFcyqzk/+qz2+Es20DbHrlv3H+z3CYsY0w8xS576PnDwSkb3HQLJDUUxsa5Y9mGYxE=
